### ISSUE TITLE
[Feature] Add git commit and tag like `npm version patch -m "New version"`

### ISSUE THREAD

**Issue by FrancisMurillo** [oo6/mix-bump#1]
Hello,

Would it be possible to add commit and tag feature similar to `npm version patch -m "Bump version patch"`? It would be a great feature so that I don't have to manually tag or make the commit message each time.

**Comment by oo6** [comment]
I've pushed a new version with these features.

You can use it as before, it automatically commit changes and tag a new version. Of course, you can also specify the message and tag with the `-m` and `-t` option.

Finally, Happy New Year!
