### ISSUE TITLE
Annotated tags for automatic github releases

### ISSUE THREAD

**Issue by matthewoden** [oo6/mix-bump#4]
So I've been using this for a bit, and kind of manually creating releases in github after tagging.

At least for github/github enterprise, this could be automated. We could generate releases from the command line by using `-a` for annotated tags, over the default simple tags.

``` elixir
def tag(version, message) do
  Command.execute("git tag -a #{version} -m #{message}")
end
```

This would change the nature of tags for users of mix bump. Not sure if it does any harm, but maybe not everyone wants annotated tags.

**Comment by matthewoden** [comment]
Any chance this change could be published?

**Comment by oo6** [comment]
@matthewoden I just released this, thanks for the follow-up. 👍
